// app/layout.js
import './globals.css';
import { Providers } from './providers';
import Navbar from './components/Navbar';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "MyShop-USER",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
